packages:
  - "packages/*"
  - "configs/*"
  - "plugins/augment/*"
  - "plugins/explore/*"
  - "plugins/vcs/*"

onlyBuiltDependencies:
  - "bun"
  - "esbuild"
  - "@moonrepo/cli"
  - "@maastrich/moonx"