# https://moonrepo.dev/docs/config/tasks
# yaml-language-server: $schema=https://moonrepo.dev/schemas/tasks.json
$schema: "https://moonrepo.dev/schemas/tasks.json"

tasks:
  lint:
    command: "biome lint"
    inputs:
      - "@group(sources)"
      - "/biome.jsonc"
      - "biome.jsonc"

  check:
    command: "tsc --noEmit"
    inputs:
      - "@group(sources)"
      - "@group(dependency-sources)"
      - "tsconfig.json"
