# https://moonrepo.dev/docs/config/project
# yaml-language-server: $schema=https://moonrepo.dev/schemas/project.json
$schema: "https://moonrepo.dev/schemas/project.json"

platform: node
language: other

workspace:
  inheritedTasks:
    exclude:
      - knip
      - format
      - format-check
